import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { Check } from "lucide-react";
import { useState } from "react";
import { useAuth } from "@/components/recomp/auth-context";
import { useOnboardingDraft } from "@/components/recomp/onboarding-context";
import { FormMessage, OnboardingHeader, OnboardingScreen } from "@/components/recomp/onboarding-ui";
import { Button } from "@/components/ui/button";
import { loadUserPreferences, trainingDefaultsForGoals, type TrainingGoal } from "@/lib/user-preferences";

const targets = [2, 3, 4, 5, 6, 7] as const; const goals: TrainingGoal[] = ["Build muscle", "Get stronger", "Lose fat", "Improve fitness", "General health"];
export const Route = createFileRoute("/onboarding/training")({ head: () => ({ meta: [{ title: "Your Training — RECOMP'D" }, { name: "description", content: "Choose your RECOMP'D training preferences." }, { property: "og:title", content: "Your Training — RECOMP'D" }, { property: "og:description", content: "Choose your RECOMP'D training preferences." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: TrainingSetupPage });
function TrainingSetupPage() { const { draft, updateDraft } = useOnboardingDraft(); const { commitPreferences } = useAuth(); const navigate = useNavigate(); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const toggleGoal = (goal: TrainingGoal) => updateDraft({ goals: draft.goals.includes(goal) ? draft.goals.filter((item) => item !== goal) : [...draft.goals, goal] }); const finish = async () => { const current = loadUserPreferences(); const height = Number(draft.height); if (!draft.height || !Number.isFinite(height) || height < 80 || height > 250) { void navigate({ to: "/onboarding/about" }); return; } setSaving(true); setError(""); try { await commitPreferences({ ...current, name: draft.name.trim() || current.name, heightCm: Math.round(height), gender: draft.gender, weeklyWorkoutTarget: draft.weeklyWorkoutTarget, weightUnit: draft.weightUnit, goals: draft.goals, ...trainingDefaultsForGoals(draft.goals), onboardingComplete: true }); updateDraft({ password: "", confirmPassword: "" }); void navigate({ to: "/", replace: true }); } catch { setError("Couldn't save your setup. Check your connection and try again."); } finally { setSaving(false); } }; return <OnboardingScreen><OnboardingHeader title="Your training" subtitle="Set the essentials. You can change these anytime." backTo="/onboarding/about" progress={2} /><div className="flex flex-1 flex-col"><div className="space-y-6">{error && <FormMessage>{error}</FormMessage>}<section><h2 className="text-sm font-extrabold">How many times do you want to train each week?</h2><div className="mt-3 grid grid-cols-6 gap-1.5">{targets.map((target) => <Button key={target} variant={draft.weeklyWorkoutTarget === target ? "choiceActive" : "choice"} className="h-12 px-0" onClick={() => updateDraft({ weeklyWorkoutTarget: target })}>{target}</Button>)}</div></section><section><h2 className="text-sm font-extrabold">Weight units</h2><div className="mt-3 grid grid-cols-2 gap-2">{(["kg", "lb"] as const).map((unit) => <Button key={unit} variant={draft.weightUnit === unit ? "choiceActive" : "choice"} onClick={() => updateDraft({ weightUnit: unit })}>{unit}</Button>)}</div></section><section><h2 className="text-sm font-extrabold">What are you working towards?</h2><p className="mt-1 text-xs text-muted-foreground">Choose any that apply.</p><div className="mt-3 flex flex-wrap gap-2">{goals.map((goal) => <Button key={goal} variant={draft.goals.includes(goal) ? "choiceActive" : "choice"} className="h-10 px-3 text-xs" onClick={() => toggleGoal(goal)}>{draft.goals.includes(goal) && <Check />}{goal}</Button>)}</div></section></div><Button variant="primary" size="xl" className="mt-auto w-full" onClick={() => void finish()} disabled={saving}>{saving ? "Saving…" : "Start training"}</Button></div></OnboardingScreen>; }