import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useState, type FormEvent } from "react";
import { useOnboardingDraft } from "@/components/recomp/onboarding-context";
import { FormField, OnboardingHeader, OnboardingScreen } from "@/components/recomp/onboarding-ui";
import { Button } from "@/components/ui/button";
import type { Gender } from "@/lib/user-preferences";

const genders: Gender[] = ["Male", "Female", "Prefer not to say"];
export const Route = createFileRoute("/onboarding/about")({ head: () => ({ meta: [{ title: "About You — RECOMP'D" }, { name: "description", content: "Add the profile details RECOMP'D needs." }, { property: "og:title", content: "About You — RECOMP'D" }, { property: "og:description", content: "Add the profile details RECOMP'D needs." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: AboutPage });
function AboutPage() { const { draft, updateDraft } = useOnboardingDraft(); const navigate = useNavigate(); const [error, setError] = useState(""); const submit = (e: FormEvent) => { e.preventDefault(); const height = Number(draft.height); if (!draft.height || !Number.isFinite(height) || height < 80 || height > 250) { setError("Enter a height from 80–250 cm"); return; } setError(""); void navigate({ to: "/onboarding/training" }); }; return <OnboardingScreen><OnboardingHeader title="About you" subtitle="Just enough to personalise your profile." backTo="/create-account" progress={1} /><form onSubmit={submit} className="flex flex-1 flex-col"><div className="space-y-6"><FormField label="Height (cm)" type="number" inputMode="numeric" min={80} max={250} value={draft.height} onChange={(e) => updateDraft({ height: e.target.value })} error={error} /><div><p className="mb-2 text-xs font-bold text-muted-foreground">Gender <span className="font-medium">(optional)</span></p><div className="grid grid-cols-1 gap-2">{genders.map((gender) => <Button type="button" key={gender} variant={draft.gender === gender ? "choiceActive" : "choice"} className="justify-start" onClick={() => updateDraft({ gender: draft.gender === gender ? "" : gender })}>{gender}</Button>)}</div></div></div><Button type="submit" variant="primary" size="xl" className="mt-auto w-full">Continue</Button></form></OnboardingScreen>; }