import { Award, CalendarDays, ChevronRight, Scale } from "lucide-react";
import { Card } from "@/components/ui/card";
import { records, recentWorkouts } from "@/data/mock-data";
import { SectionHeading, SummaryRow } from "./core";
import { TrainingPriority } from "./training-widgets";

export function ProgressOverview() {
 return <div className="space-y-5"><TrainingPriority compact/><section><SectionHeading>Calendar</SectionHeading><Card className="p-4"><div className="mb-3 flex items-center gap-2 text-sm font-bold"><CalendarDays className="size-4 text-primary"/>September</div><div className="grid grid-cols-7 gap-1 text-center">{[18,19,20,21,22,23,24].map((day,i)=><div key={day} className="space-y-1.5"><div className="text-[0.62rem] text-muted-foreground">{['F','S','S','M','T','W','T'][i]}</div><div className={`grid aspect-square place-items-center rounded-full text-xs font-bold ${[1,3,6].includes(i) ? 'bg-primary text-primary-foreground' : 'bg-secondary text-muted-foreground'}`}>{day}</div></div>)}</div></Card></section><section><SectionHeading>Personal records</SectionHeading><Card className="divide-y divide-border px-4">{records.map((record)=><div key={record.exercise} className="grid min-h-14 grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3"><Award className="size-4 text-primary"/><div className="text-sm font-semibold">{record.exercise}</div><div className="text-right"><div className="text-sm font-black tabular-nums">{record.value}</div><div className="text-[0.62rem] text-muted-foreground">{record.date}</div></div></div>)}</Card></section><section><SectionHeading>Bodyweight</SectionHeading><Card className="grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 p-4"><div className="grid size-10 place-items-center rounded-xl bg-accent text-primary"><Scale className="size-5"/></div><div><div className="text-xl font-black">101.2 <span className="text-xs text-muted-foreground">kg</span></div><div className="text-xs text-primary">−0.8 kg this month</div></div><ChevronRight className="size-4 text-muted-foreground"/></Card></section><section><SectionHeading>Workout history</SectionHeading><Card className="divide-y divide-border px-4">{recentWorkouts.map((workout)=><SummaryRow key={workout.name} title={workout.name} subtitle={`${workout.date} · ${workout.duration}`} meta={workout.sets}/>)}</Card></section></div>
}
