/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildRouteImport } from './routes/build'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as WorkoutRouteImport } from './routes/workout'
import { Route as BuildIndexRouteImport } from './routes/build.index'
import { Route as BuildPreviewRouteImport } from './routes/build.preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutRoute = WorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildIndexRoute = BuildIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuildRoute,
} as any)
const BuildPreviewRoute = BuildPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => BuildRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/build': typeof BuildRouteWithChildren
  '/progress': typeof ProgressRoute
  '/workout': typeof WorkoutRoute
  '/build/preview': typeof BuildPreviewRoute
  '/build/': typeof BuildIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/progress': typeof ProgressRoute
  '/workout': typeof WorkoutRoute
  '/build/preview': typeof BuildPreviewRoute
  '/build': typeof BuildIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/build': typeof BuildRouteWithChildren
  '/progress': typeof ProgressRoute
  '/workout': typeof WorkoutRoute
  '/build/preview': typeof BuildPreviewRoute
  '/build/': typeof BuildIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/build' | '/progress' | '/workout' | '/build/preview' | '/build/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/progress' | '/workout' | '/build/preview' | '/build'
  id:
    | '__root__'
    | '/'
    | '/build'
    | '/progress'
    | '/workout'
    | '/build/preview'
    | '/build/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildRoute: typeof BuildRouteWithChildren
  ProgressRoute: typeof ProgressRoute
  WorkoutRoute: typeof WorkoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build/': {
      id: '/build/'
      path: '/'
      fullPath: '/build/'
      preLoaderRoute: typeof BuildIndexRouteImport
      parentRoute: typeof BuildRoute
    }
    '/build/preview': {
      id: '/build/preview'
      path: '/preview'
      fullPath: '/build/preview'
      preLoaderRoute: typeof BuildPreviewRouteImport
      parentRoute: typeof BuildRoute
    }
  }
}

interface BuildRouteChildren {
  BuildPreviewRoute: typeof BuildPreviewRoute
  BuildIndexRoute: typeof BuildIndexRoute
}

const BuildRouteChildren: BuildRouteChildren = {
  BuildPreviewRoute: BuildPreviewRoute,
  BuildIndexRoute: BuildIndexRoute,
}

const BuildRouteWithChildren = BuildRoute._addFileChildren(BuildRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildRoute: BuildRouteWithChildren,
  ProgressRoute: ProgressRoute,
  WorkoutRoute: WorkoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
